// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkoSQOAsiXCda9vEEN0uBoQFmbdZgddU',
    appId: '1:676173772962:web:89c7ba9576610797af3ffb',
    messagingSenderId: '676173772962',
    projectId: 'katyayani-895b6',
    authDomain: 'katyayani-895b6.firebaseapp.com',
    storageBucket: 'katyayani-895b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc6d5vmLgAbIaC6rfOYwsGi3YbQVvUi38',
    appId: '1:676173772962:android:61d9e8c85218a042af3ffb',
    messagingSenderId: '676173772962',
    projectId: 'katyayani-895b6',
    storageBucket: 'katyayani-895b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSN3oiS2UcmMgXC4r6enmluDFKBKn-JZA',
    appId: '1:676173772962:ios:4f023b47e33c68a6af3ffb',
    messagingSenderId: '676173772962',
    projectId: 'katyayani-895b6',
    storageBucket: 'katyayani-895b6.firebasestorage.app',
    iosBundleId: 'com.example.agro',
  );
}
